### ISSUE TITLE
Unable to delete Road Assessment database after creation 

### ISSUE THREAD

**Issue by tinvaan** [WiseEarthTechnology/CrisisCommunicator#17]
After creating an "Asses Road" at a location , I'm unable to delete the same later. The delete option leads me to the registration page and even after registering , the database is not removed

**Comment by swiftarrow** [comment]
You've stumbled on a bug!  This was previously reported on the old
repository and has not been brought over yet.

Thanks for re-reporting it!

Note that the delete action as it currently stands (for all of the entries)
is not what it should be. If you see  Issue _#2_, some thinking needs to go
into the definition of a single class / single app that will hold all the
different record types.

Also mentioned there is that the Delete function needs to be a flag in the
class; if set, it is ignored, but not removed from the database.  This is
for the purpose of post-disaster analysis of the response: the database
needs to preserve a complete record of all transactions.

Thanks, Love, Peace,
Link

**Comment by tinvaan** [comment]
Well if it's a bug , I'd like to get it assigned to myself and attempt a fix . What next ?

**Comment by swiftarrow** [comment]
Sure you can fix it!  Also think about that Issue #2, we need to evolve the
code to have the functionality described there.

Thanks, Love, Peace,
Link

**Comment by swiftarrow** [comment]
Cool!  That's great.  I think there's one pull request before this one, so if you can re-base this one after we've merged that, then we can pull it in.  Wait till we've merged that one though :)

**Comment by varrunr** [comment]
@harishnavnit Your pull request #19  attempts to fix both issue#17 and issue#3. Lets leave the license part of it alone for now. There is a pending pull request to remove the license. You may want to change your pull request to make changes _only_ for issue#17.

**Comment by tinvaan** [comment]
Sorry , I removed the license from assessment/views.py file aswell . But otherwise , I think now my pull request deals only with Issue #17 . I hope this is fine .

**Comment by swiftarrow** [comment]
If anyone gets a chance to look at this, please do.  I'm traveling for next
two weeks, and might not be able to.

Thanks, Love, Peace,
Link

**Comment by swiftarrow** [comment]
Hi from Bangkok!  Has anyone had the chance to review this?  Has trunk moved or is it safe to merge this?

**Comment by varrunr** [comment]
Please see my latest comment on pull request #19 , I'm waiting for @harishnavnit to fix those, I'd rather that he discard the pull request and submit a new one with just the changes for this issue. @harishnavnit , do you have an update on that?

**Comment by swiftarrow** [comment]
@varrunr thanks for the update!  @harishnavnit Please see Varrun's comments :)

**Comment by tinvaan** [comment]
I saw @varrunr 's comment and was working on the same , but got really busy with the end semester lab exams etc. I will do it as soon as I find some time. Sorry for the delay .

**Comment by swiftarrow** [comment]
BTW, how did your exams go?

**Comment by tinvaan** [comment]
:-1:

**Comment by swiftarrow** [comment]
Sorry to hear that!

**Comment by swiftarrow** [comment]
I think this has been fixed?
