### ISSUE TITLE
Add installation script

### ISSUE THREAD

**Issue by varrunr** [WiseEarthTechnology/CrisisCommunicator#24]
INSTALL.md assumes a developer is going to install the app instead of a user on an actual webserver. There should instead be a script which automates the install(through a make file/shell script), and the dev specific instructions should go into the dev wiki.

**Comment by swiftarrow** [comment]
That's something I can do!

**Comment by swiftarrow** [comment]
@varrunr the intended installation would be on a single device, not on a central webserver.  I can write an install script to set up the dev environment anyway.

Incidentally, I was in talks with an organization here that works on projects to do with GIS, and they like this project.  They have put me in touch with an accelerator, in Feb we should know more on that front.

**Comment by varrunr** [comment]
Yes, I understand, but each device hosts a web server right now which listens on localhost.  To be scalable it would be wise not to use the default lightweight web server provided by Django and use Apache/Nginx.

**Comment by swiftarrow** [comment]
@varrunr, Good Point!  Can you help flesh out a decision over here:
https://github.com/WiseEarthTechnology/CrisisCommunicator/wiki/Which-Server-stack-should-be-used-for-the-CrisisCommunicator%3F
Thanks!

**Comment by swiftarrow** [comment]
@varrunr so I guess we'll recommend lighthttpd/nginix plus SQLite for a "production" setup?  

I should also script the setup for a local open street maps.

**Comment by varrunr** [comment]
> @varrunr so I guess we'll recommend lighthttpd/nginix plus SQLite for a "production" setup?

If we're going to support them we need to also know how to enable use of Django(rather CGI) with these web servers.

> I should also script the setup for a local open street maps.

That would be great.

**Comment by swiftarrow** [comment]
I found a great resource to set up Django to run properly for production:

http://grokcode.com/784/how-to-setup-a-linux-nginx-uwsgi-python-django-server/

I'll hold off on scripting that.  If someone wants to, they can set it up pretty easily.

I'm actually scripting the dev environment setup right now to make it easier for people to jump on board.  :)

**Comment by swiftarrow** [comment]
Done!  We now have a completely new install pathway, using the Adorno script.  It's totally clean and super-easy!  :)
