### ISSUE TITLE
Which web server to use?

### ISSUE THREAD

**Issue by varrunr** [WiseEarthTechnology/CrisisCommunicator#25]
Note: Moving to issue rather than wiki for better discussion.

Wiki: https://github.com/WiseEarthTechnology/CrisisCommunicator/wiki/Which-Server-stack-should-be-used-for-the-CrisisCommunicator%3F
# Scenario

The CrisisCommunicator is a webapp that is deployed on individual nodes and serves exclusively to localhost.  Each node interacts with the others via a mesh network.

Everything has to be extremely lightweight.

Therefore, the question is which server stack should be used?  On this discussion page we'll try to arrive at an optimum stack.

There are a number of alternatives.  Please list pros / cons / opinions under each heading.

**Comment by varrunr** [comment]
On `gunicorn`,
**Linkesh:** I don't know much about this, but I've read where this is recommended.  Your thoughts?
**Varrun**: gunicorn looks interesting and seems to have out-of-the-box support for django. However, I have not heard of this before, it might be better to go with a popular one so we can get support from the community.

**Comment by varrunr** [comment]
On `Apache + mod_python + MySQL`
**Linkesh:**  I think we can nix this... it's not really a viable option.
**Varrun** I agree, not an option, since Apache might take up too much memory. MySQL is out of the picture.

**Comment by swiftarrow** [comment]
In light of http://grokcode.com/784/how-to-setup-a-linux-nginx-uwsgi-python-django-server/ I think we can close this discussion.

Nginx and uWSGI seems to be the preferred method for lightweight deployment on servers.
