### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by tinvaan** [WiseEarthTechnology/CrisisCommunicator#26]
I find this error when I try logging in by pressing the "Register" button without filling in the "User ID" and "Name" field . 
I think when a user doesn't enter his "User ID" and "Name" and hits "Register" , rather than showing the message "You have an error" , one could splash some alternative message like say , "Enter User ID and Name first". 
The first time I encountered this message , I was a little confused . I think the word error can be misleading at times .
![login_page](https://f.cloud.github.com/assets/5815030/1878064/4be3465c-7934-11e3-96f7-9c8d677079c2.png)

**Comment by tinvaan** [comment]
Can @swiftarrow  or @varrunr  verify if this works fine ? I don't trust my system :P

**Comment by swiftarrow** [comment]
@harishnavnit can you join us on freenode / #CrisisCommunicator ?
