### ISSUE TITLE
Trivial: The License Header in the code files

### ISSUE THREAD

**Issue by swiftarrow** [WiseEarthTechnology/CrisisCommunicator#3]
Please remove the header to the files which contains the entire license text, and insert in it's place, the following, simple header:

```
Filename: <insert filename> 
Authors: <insert authors>
Copyright: Wise Earth Technology
This file is part of the CrisisCommunicator Project.  
It is licensed under the Peaceful Open Source License.  
Please see the license terms in PeaceOSL.txt
```

**Comment by swiftarrow** [comment]
Harish, I don't think you can add your name as author in the code unless / until you have contributed significant changes to the code.  Changing this license header is a great help, but it doesn't constitute authorship of the code.

I'm sure you understand. I unfortunately pre-maturely merged your pull request, so I have to ask you to do another pull request where you fix this issue.

Also, separating the authors names by a comma would be good.

Thanks!

**Comment by swiftarrow** [comment]
Harish, I've reverted your commits, can you separate the requirements commit into it's own pull request so we can get that in, and then fix the license header later?  Thanks!

**Comment by tinvaan** [comment]
I'll get it done , thanks :)

R.Harish Navnit
The Enigma http://harishnavnit.wordpress.com

**Comment by swiftarrow** [comment]
I lost track, this has been fixed properly now, right?

**Comment by varrunr** [comment]
The license header has been removed from the files. As per my comment on the original pull request, I would have liked to see variables to track metadata in the files so that its easier to generate documentation. However, its not that important, and can wait till a later day when the app reaches a stable state.
